### ISSUE TITLE
Better and complete descriptions of the metrics under GMD

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/wg-gmd#1]
Hey all

Some of the metrics under GMD have incomplete information about how to calculate them. Example:
- [issue-resolution-efficiency](https://github.com/chaoss/metrics/blob/master/activity-metrics/issue-resolution-efficiency.md): how do we say that an issue has been abandoned?
- [open-issue-age](https://github.com/chaoss/metrics/blob/master/activity-metrics/open-issue-age.md): do we calculate the average open issue age or should we chart each open issue individually in a graph along with the days since they were opened.
- [closed-issue-resolution-duration](https://github.com/chaoss/metrics/blob/master/activity-metrics/closed-issue-resolution-duration.md): here, the description seems wrong.

**Comment by germonprez** [comment]
Hi @aswanipranjal, you're right :) 

The way that this has evolved as been for us to capture the metrics that people would like to see (even if there is not necessarily a known implementation). In essence, we have cast a wide net to listen to what people would like. 

That said, as work in places like the GMD workgroup find ways to implement in any respective technology (GL, Augur, Kibble), they can update the metric template.

**Comment by aswanipranjal** [comment]
@germonprez, it is a wide net indeed :P I am also trying to implement them in manuscripts according to my understanding. I'll update on them once I have a better understanding and I solidify my ideas.

**Comment by jgbarah** [comment]
Since all child issues are closed, I think we can close this one as well. Please reopen if you feel that's needed.
