### ISSUE TITLE
require DCO for all new commits

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-gmd#109]
This issue is to activate [protobot/dco](https://github.com/apps/dco) (or similar bot) to check that all commits have a sign-off. The CHAOSS Project Charter requires that all contributions are signed-off. 

For users of the git command line interface, a sign-off is accomplished with the `-s` as part of the commit command: `git commit -s -m 'This is a commit message'`

For users of the GitHub interface, a sign-off is accomplished by writing `Signed-off-by: Your Name <YourName@example.org>` into the commit comment field. This can be automated by using a browser plugin like [scottrigby/dco-gh-ui](https://github.com/)

**Comment by jgbarah** [comment]
I will try to work on this during this week.

**Comment by tobie** [comment]
I'm confused as to how a DCO is appropriate for what is essentially non-code textual content. I'm also very confused about the licensing choice for this repository. Why MIT and not a CC-type license plus a patent attribution?

This might not be the right forum to discuss that, but the real value of the work that's happening here doesn't fall under copyright laws. That work is the description of the metrics, and those are patentable ideas. If anything, that's what should be protected here.

**Comment by germonprez** [comment]
The DCO and licensing choice are what are described in the charter: 

https://chaoss.community/about/charter/

These were decisions that were prescribed at the start of the project -- as hosted at the LF.

**Comment by tobie** [comment]
Yes. I read the charter. These feel like really strange defaults for such a project.

Imho, they make contributing more difficult for a community that isn't as technically savvy as pure developers without the only real potential threat given the type of work produced: patents around metrics.

**Comment by germonprez** [comment]
I hear your point on the overhead and I share the same concern. There's just not much we can do about this -- without modifying the charter. I can re-start a conversation with legal but I think that's the only path right now.

**Comment by tobie** [comment]
Doesn't requiring a DCO prevent any contribution from the web interface? If that's the case, I think it's worth revisiting the legal aspects.

**Comment by germonprez** [comment]
It wouldn't. However, it would require manual entry of a signed-off line into a commit.

**Comment by tobie** [comment]
I could have read the initial message from @GeorgLink and avoided that last exchange. Apologies. In that case, whoever is going to do the work should make the call. I'm happy to sit on a call with legal to discuss the real needs of this project given what's actually produced, and help carry out the charter changes this would induce, but I can't be the one initiating this.

**Comment by germonprez** [comment]
Sounds good. Thanks @tobie. I'm always in search of ways to work with the needs at the LF and community while at the same time managing the overhead in the project.

**Comment by GeorgLink** [comment]
I agree that we should have appropriate licensing and little overhead. @tobie and @germonprez  summarized the debate well.

To provide background and if I remember correctly, we have MIT for the metrics repositories, because (1) we were expecting sample code and wanted it to be licensed liberally, and (2) MIT is liberal enough to apply to documentation such as we are creating in describing metrics. Rather than have CC for the docs and MIT for code snippets, we have one single license.

**Comment by GeorgLink** [comment]
> I will try to work on this during this week.

@jgbarah, I can activate the DCO bot on the chaoss/wg-gmd repo. 
This requires then all contributors to sign-off on their commits. No other change needed.

I have piloted the DCO bot on the chaoss/governance repository and can report that it works well. The most trouble is if someone forgets to sign-off. I use a browser plugin to automate the sign-off in the browser when I use the GitHub UI. For a single commit locally, `git commit amend -s` adds the sign-off later.

I propose a change to the chaoss/governance repo CONTRIBUTING.md to explain how to sign-off for DCO.
https://github.com/chaoss/governance/pull/100/files

**Comment by sgoggins** [comment]
We discussed this in the meeting and agreed to accept it into our working group.

**Comment by GeorgLink** [comment]
Great. DCO bot is active 👍

**Comment by jgbarah** [comment]
Thx @GeorgLink !!

**Comment by GeorgLink** [comment]
You are welcome 👍
