### ISSUE TITLE
What are sub-projects?

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-gmd#11]
There are a number of ways subprojects can be defined.  I think we need a more clear definition of what subprojects are here: https://github.com/chaoss/wg-gmd/blob/master/activity-metrics/sub-projects.md

Possibly following a discussion

**Comment by jgbarah** [comment]
I agree. Besides, I see the number of projects more like an organizational way (how the project decides to think about itself) than something related to activity, or to GMD. What do you think?
