### ISSUE TITLE
[metrics] Difference between Proposals_Accepted and Proposal_Acceptance

### ISSUE THREAD

**Issue by Polaris000** [chaoss/wg-gmd#117]
In the code development focus area, specifically, in [code_development.md](https://github.com/chaoss/wg-gmd/blob/master/focus_areas/code_development.md), there is a mention of two metrics:
- [Proposals_Accepted](https://github.com/chaoss/wg-gmd/blob/master/metrics/Proposals_Accepted.md) (Goal: Activity)
- Proposal_Acceptance (Goal: Efficiency)

I'm finding it difficult to understand the difference between these. I could not find a separate page for the second metric(hence, I have n't linked it to its page).

Or is there no difference and just an accidental usage of different naming conventions? 
Could someone please explain?

**Comment by jgbarah** [comment]
Thanks for the comment. `Proposals_Accepted` is the total number of proposals that finished by accepting the proposed change. `Proposal_Acceptance` is the ratio of proposals that finished by accepting the change to the total number of proposals. I'm sorry the latter one is still not detailed (does not have its own page). We hope to work with it soon.

Please, close this issues if you feel the answer is dealing with your concern.

**Comment by Polaris000** [comment]
Thanks for the reply.

> Metric Proposal_Acceptance(Period): How many proposals are finally accepted.

This line from the code_development.md file does not talk about a ratio. I'll send a pull request if this has to be updated. Let me know.

**Comment by Polaris000** [comment]
Also, there is another metric defined under the goal of efficiency:
> Summary metric: Proposal_Acceptance_Ratio(Period): Which fraction of new proposals are finally accepted?

This sounds quite similar to the definition you gave for `Proposal_Acceptance`.

**Comment by jgbarah** [comment]
OK, I see now. Sorry for my error: you're right, `Proposals_Accepted` in goal `Activity` should be the same as `Proposal_Acceptance` in goal `Efficiency`. Please, feel free to submit a pull request to fix that, and sorry for the noise.

**Comment by Polaris000** [comment]
Thanks for the reply @jgbarah. I am not sure I perfectly understand what is to be done.
When you said:  
> Proposals_Accepted in goal Activity should be the same as Proposal_Acceptance in goal Efficiency.

you probably meant that both metrics should refer to the same thing. Since in the current version of the file, both metrics point to more or less the same thing (the reason for raising this issue in the first place), I could replace `Proposal_Acceptance` in goal `Efficiency` with `Proposals_Accepted` in goal `Activity` (having `Proposals_Accepted` in two places) since the former already has its own page.  

Or could do it the other way around (having `Proposal_Acceptance` in two places), which would ultimately mean creating another page for `Proposal_Acceptance`. 

I'll create a pull request to fix this issue. If what was supposed to be done is something completely different, please suggest those changes in the review.
