### ISSUE TITLE
Metric Question should be 'Pull Request Merged'

### ISSUE THREAD

**Issue by sarvesh211999** [chaoss/wg-gmd#120]
in https://github.com/chaoss/wg-gmd/blob/master/focus_areas/code_development.md
the metric 'Pull Requests Merged' has question 'What is the number of code commits?' that should be 'What is the number of pull request merged?' 

Reason: Many Commits can be directly done by the authorized person without creating pull_request.

**Comment by Polaris000** [comment]
I agree.
@jgbarah?

**Comment by jgbarah** [comment]
Yesssss. That's an error, very likely because of too much copy&paste. Please, provide a fix if you want.

**Comment by Polaris000** [comment]
@sarvesh211999 are you working on this issue?

**Comment by sarvesh211999** [comment]
Yeah.

**Comment by Polaris000** [comment]
@sarvesh211999 , can you close this issue as the corresponding pull request appears to have been merged?

**Comment by GeorgLink** [comment]
@Polaris000 here is a neat little trick for automatically closing an issue when a pull request is merged: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by Polaris000** [comment]
Thanks @GeorgLink for the information. Though I am aware of this feature and use it quite often myself, I think I am missing the point. Since I neither have write access to this repository nor am I the author of this issue, won 't it be impossible for me to close this issue?

**Comment by GeorgLink** [comment]
Sorry for the confusion. I always like to point this feature out because anyone can write a comment on a pull request before it gets merged to automate the closing of issues.

This was for future reference, not for this particular issue.
