### ISSUE TITLE
[metrics] Understanding Contributing Organizations and Sub-Projects metrics

### ISSUE THREAD

**Issue by Polaris000** [chaoss/wg-gmd#133]
The definitions given for these metrics in their respective files are quite vague. What is meant by a subproject? 

What is a contributing organization?
These questions were addressed in issue #10 and #11, which was a long time back. Is there a better and clearer way to define them?
The links to the metrics' pages are:
- https://github.com/chaoss/wg-gmd/blob/master/metrics/organizations.md
- https://github.com/chaoss/wg-gmd/blob/master/metrics/organizations-new.md
- https://github.com/chaoss/wg-gmd/blob/master/metrics/sub-projects.md

**Comment by Polaris000** [comment]
@GeorgLink @jgbarah

**Comment by jgbarah** [comment]
We need to work on that. But in any case, please remember that we're working sort of top-down, from a focus area, to the (knowledge or actionable) goals for that focus area, to the questions that may help to reach those goals, to the metrics that can help to answer those goals. Therefore, we need to consider this (organizations and subprojects) in the context of the relevant focus area / goal / question.

I would close this for now, but at the same time, find out in which focus areas organizations and subprojects are relevant, and reopen the discussion in that context.

**Comment by Polaris000** [comment]
Thanks for the reply! 
> I would close this for now, but at the same time, find out in which focus areas organizations and subprojects are relevant, and reopen the discussion in that context.

Will do!
