### ISSUE TITLE
Who can be considered a maintainer for a project?

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/wg-gmd#14]
AFAIK a maintainer is a user who has PUSH privileges to a codebase and how can approve of the changes made by other users. Currently the users are being divided into:  None, Owner, Collaborator, Contributor and Member. Out of these, I think Only Owner of the repo can be considered as a maintainer because they'll be deciding which code is included into the project or not.

Apart from that, we can set some conditions that if a user X has contributed Y times to a project and is active in solving issues then they can be considered as a maintainer.

We can also set a condition such as `Issues.First:_Response(maintainers=['Owner', 'Memberr'])` as Jesus @jgbarah suggested [here during our meeting](https://github.com/aswanipranjal/gsoc-manuscripts/blob/master/IRC-transcripts/IRC-chat-13-06-2018.txt#L182). 
[Start of the discussion](https://github.com/aswanipranjal/gsoc-manuscripts/blob/master/IRC-transcripts/IRC-chat-13-06-2018.txt#L151).

This is relevant because for calculating #8 , we need to know who the maintainer is.

**Comment by jgbarah** [comment]
Hi, @aswanipranjal when you say "Currently the users are being divided into: None, Owner, Collaborator, Contributor and Member", you mean in the GitHub API, right?

**Comment by aswanipranjal** [comment]
Yes, @jgbarah.

**Comment by jgbarah** [comment]
i'm closing this for now, since this is part of a broader discussion on the concepts that we deal with for the metrics. Please, feel free to reopen if you think it is better to follow on here.
