### ISSUE TITLE
Development Velocity Meta Metric

### ISSUE THREAD

**Issue by BenLloydPearson** [chaoss/wg-gmd#15]
Based on the discussions we had in the working group meeting last week. Here is my proposed meta-metric (super-metric) for development velocity.

# Background
When evaluating the success of an open source community, one of the most basic things to evaluate is how quickly new code or content is produced and merged into the mainline project, and whether this rate is increasing, decreasing, or staying constant.

# Components
* Code Commits
* Code Merge Duration

# Outcome
**Development Speed:** fast, slow, halted. This meta-metric can either be relative and compare two separate projects (i.e which project is faster/slower) or two points in time for the same project, or it can be based on an established baseline that is specific to the project, technology, or software development practices at large. 
**Development Acceleration:** accelerating, decelerating, constant. This is a relative meta-metric that compares the development speed at two points in time for the same project.

# Use Cases:
A community manager wants to evaluate the impact of hosting a series of developer events to see if development activity is increasing as a result of them.

A strategist or software architect is evaluating multiple open source components to integrate into company projects. They want to identify which community has a greater level of development activity and whether each project is increasing or decreasing in activity.

# Example Value Statements
* Development is fast, but decelerating.
* Development is slow and has been constant for 3 months.
* Development is slower than it was last year, but is accelerating.
* Development has stalled for 6 months.
* Development of project A is faster than development of project B.

# Formula
**Development Speed:** (Code Commits) / (Code Merge Duration). This factors both component metrics and expresses a number that is higher for projects that have larger number of commits and smaller lengths of time to get code committed. I.e. faster projects have a higher number. 

**Development Acceleration** - This simply compares development speed from two different points in time.

**Comment by sgoggins** [comment]
@BenLloydPearson and @germonprez : If you take a look at the default representation of most metrics on the Augur project, we have time series data presented by default. http://dev.augurlabs.io/?repo=rails+rails

**Comment by sgoggins** [comment]
I think we want to have definitions put together in a markdown file.

**Comment by sgoggins** [comment]
Maybe we add "Velocity" as straight up "event counting" for a particular metric.

**Comment by jgbarah** [comment]
@BenLloydPearson, since now we have [use cases](https://github.com/chaoss/wg-gmd/tree/master/use_cases), what do you think about converting this into a use case, for further discussing it? If you want, I can open the issue to start the discussion.

**Comment by sgoggins** [comment]
@BenLloydPearson & @jgbarah : Ben's proposal "sounds" to me more like a straight up metric than a use case ... I say this mostly because I cannot think of, off the top of my head, the various different actors who would be interested in velocity outside the context of a family of other metrics. ... by itself, I am not sure its a "use case"; but I think it might be part of another use case. 

My sense of things could be wrong.  @BenLloydPearson : How are you thinking about your suggestion?

**Comment by jgbarah** [comment]
I was thinking of a very simple use case, like "Learning about how quickly new code or content is produced and merged into the mainline project" (borrowing from a sentence in the Background section). From this, questions are already mentioned, and we could (maybe) discuss about some other metrics. But I was just wondering... Now, I'm sort of focused on use cases, and you know, when you have a hammer... ;-) So, @BenLloydPearson what do you think?

**Comment by BenLloydPearson** [comment]
I don't really think this fits into the idea of a use case because I think it would likely have value for many  use cases. With that said, I don't really have time to develop this idea further, and I suspect that the use case model might be better for providing a higher level understanding that what I'm proposing here. I'll close this for now and reopen it if I think the idea is worth revisiting.

**Comment by jgbarah** [comment]
OK, @BenLloydPearson, thanks. In any case, let's keep this idea in mind when we do the goal-question-metric for the different focus areas.
