### ISSUE TITLE
Standardized names for entities 

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-gmd#25]
From Mailing List

**dmg**

I would like to suggest that as part of CHAOSS, there is also an attempt to standardize how to call an entity
in a repository/database. Note these are not the names of the entities, but their abbreviations.

This is what I mean:

1. Entities.
A commit has a commit id,  "author" and a "committer" and a  authorship-date, and a committing date.
What should we call them?

cregit calls them: cid, author, committer, autdate, comdate,
a subderived entity: we prefix with an identifier:
   author => autemail, autname

2. Counts.

What should counts be called? We prefix the entity with n;
ncommits, nauthor, nfiles, etc.

**Manrique**
It sounds like a reasonable expectation, so thanks Daniel for opening the discussion.

From time to time I have been thinking about proposing schema.org as baseline vocabulary.

There are some already defined that could be interesting to check:

https://schema.org/Person
https://schema.org/SoftwareSourceCode
https://schema.org/Organization
https://schema.org/Comment
https://schema.org/Dataset
https://schema.org/DataFeed
https://schema.org/Question

I think most of software development related activity couybe mapped to CreativeWork concept:
https://schema.org/CreativeWork

Perhaps my Semantic Web "background" is always trying to find a place for all these years of standardizing vocabularies. Another potential interested approach is SIOC:
http://rdfs.org/sioc/spec/

Of course, we should agree about names and what they mean. For example, "commit", can be interpreted very differently:
https://blog.bitergia.com/2014/03/07/commits-that-metric/

**Comment by jgbarah** [comment]
Thanks for putting this together, @klumb. Can we consider this is being addressed by #24 and maybe #34 for now, and close this issue?

**Comment by klumb** [comment]
Yes, I believe we can close this.
