### ISSUE TITLE
Explain in the main README.md what is GMD

### ISSUE THREAD

**Issue by jgbarah** [chaoss/wg-gmd#35]
This working group is about Growth-Maturity-Decline metrics. But it is not always obvious which metrics fall in this category. I suggest to have some text in the main `README.md` file of this repo stating what GMD is. We can start with a pull request on that file, and if needed have a discussion on that pull request.

@sgoggins could you please write a first draft, since I think you're the person more familiar with the concept of GMD?

**Comment by sgoggins** [comment]
@jgbarah : Yes, I will do that today.

**Comment by jgbarah** [comment]
I think this is closed by #49, closing.
