### ISSUE TITLE
Clean-up repository

### ISSUE THREAD

**Issue by jgbarah** [chaoss/wg-gmd#4]
We still have some Markdown files in the activity-metrics directory corresponding to metrics that are not used in GMD. I think we should remove them. I didn't just in case I'm missing something... Please, anyone interested, comment here. If we agree, I can do the job later (but prs by anybody are welcome).

**Comment by klumb** [comment]
As part of aligning and defining CHAOSS processes, I can start working on this.

**Comment by jgbarah** [comment]
I think this is done for now, thanks to the work by @klumb and others. Thanks!!!
