### ISSUE TITLE
Add risk and value as new focus area for this working group

### ISSUE THREAD

**Issue by jgbarah** [chaoss/wg-gmd#41]
In our weekly meeting we decided to accept value and risk as two new focus areas for this GMD working group. We need to include them in `README.md`, `gmd_metrics.md`, and copy the directories with their current data in our `focus_areas` directories.

**Comment by jgbarah** [comment]
@sgoggins I understood you were to take care of this, so I'm assigning this ticket to you. If I'm wrong, just reassign it to me, please.

**Comment by sgoggins** [comment]
@jgbarah : yes. Me.
