### ISSUE TITLE
Refine code development focus area

### ISSUE THREAD

**Issue by jgbarah** [chaoss/wg-gmd#44]
Following the top-level approach that we intend to use for defining metrics, we will start by refining goals, questions and metrics in the code development focus area. First, we will better define scope and goals. Then, we will work on the questions to inform those goals. Than, we will find out which metrics can help to answer those questions. We will use this ticket for general discussions. When we reach a general consensus, we will work on pull requests to modify the file in the `focus_areas` directory devoted to code review. Details and specific wording will be discussed in those pull requests.

**Comment by jgbarah** [comment]
Let's start with defining the scope for this focus area. From my memories of the meeting today, we could define as "Aspects related to how the source code changes over time, and the mechanisms that the project has to perform and control those changes".

What do you think about this?

**Comment by jgbarah** [comment]
With respect to goals for this focus area, again from my memories from our last meeting:

* Learning how effective new code is merged into the code base
* Learning about the processes to improve/review quality that are used (for example: testing, code review)

Add your goals to this list ;-) (or comment on how appropriate you find these).

**Comment by germonprez** [comment]
@jgbarah, thanks for this. I agree with the scope for this as: Aspects related to how the source code changes over time, and the mechanisms that the project has to perform and control those changes. 

Further, regarding the specific goals that you provide are great. +1

**Comment by jgbarah** [comment]
Thanks, @germonprez! @sgoggins do you think we can merge this?

**Comment by jgbarah** [comment]
I've started a pull request, #59, implementing the proposed goals and scope.

**Comment by jgbarah** [comment]
Now we have another pull request for an specific metric #72.

**Comment by sgoggins** [comment]
I think we merged all the related pull requests, so I am not sure if we can close this.  I think so?

**Comment by sgoggins** [comment]
Closing issue as this is well represented now.
