### ISSUE TITLE
Prepare GSoC '18 Proposal

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-gmd#51]
Just like the title says...

January 15 20:00 UTC | Mentoring organizations can begin submitting applications to Google
February 6 20:00 UTC | Mentoring organization application deadline

**Comment by jgbarah** [comment]
Let's keep it here (proposal from the GMD meeting today), until we start working on proposals, when we can open issues in the chaoss/governance repo.

**Comment by germonprez** [comment]
Update. This is in progress from the Google Organization side. I need projects from you.

**Comment by jgbarah** [comment]
Update. We have some pull requests with ideas. @germonprez will go through them.

**Comment by sgoggins** [comment]
Next step is more detailed project description and microtasks.

**Comment by GeorgLink** [comment]
> Next step is more detailed project description

Less detail about the project and more specifics about the project idea. Two paragraphs would hopefully suffice.

> micro-tasks

Feel free to reuse the same from last year. 
Add a link to it from the idea page.

**Comment by jgbarah** [comment]
Proposal done.
