### ISSUE TITLE
Make README.md consistent with D&I working group

### ISSUE THREAD

**Issue by jgbarah** [chaoss/wg-gmd#55]
During the CHAOSS board meeting today it was proposed that WGs have a consistent README file, that refers clearly to CHAOSS, to other WGs, to how to contribute, and access to results produced by the WG.

It was also proposed that maybe we could use [Richard Litt's Best Practices for README](https://github.com/RichardLitt/standard-readme).

Thx to @BenLloydPearson for the proposal, and for convincing use this is important.

There is a companion issue for this in the D&I working group: chaoss/wg-diversity-inclusion#127

**Comment by BenLloydPearson** [comment]
Thanks @jgbarah 

# Readme.md Structure
* Intro - Needs a one-line description, one paragraph description, and a short section that links to D&I metrics repo and explains how this repo fits into overall CHAOSS metrics effort.
* Table of Contents - Clickable links at the top are a lifesaver :-)
* Background - A lot of the current content at the top of the repo will be moved here and expanded on.
* Usage - Should contain the repository structure information with additional detail about the concepts behind focus areas, use cases, implementations and all other important elements of the repo with appropriate links.
* Contribute - All of the content that references participation will be moved here and standardized with D&I repo
* License - A simple statement of the license that will be standardized with D&I repo

# Repository Structure

Additionally, I think it would be good to examine how the content of the directories is presented:

* metrics, focus_areas - These need a Readme.md that describes the content of the directory with appropriate links
* implementations - the readme here does a great job explaining how to do things, but doesn't explain why I would want to or what the result would be.
* use_cases - This Readme is really great! I just wanted to state that for the record :-)


# Steps to Resolve

I think the best approach would be to create one PR for the README changes, followed by a series of PR's for each of the directories. If we have consensus on the Readme.md changes I can get started on them. I'll do my best to retain all of the information you have, and I'll just present it under this new structure. With that said, there are likely some things I'll need help on with the details so I'll make sure we're on the same page with them.

**Comment by germonprez** [comment]
@foundjem and I will take this on

**Comment by foundjem** [comment]
Hello Matt,
Attached, please find a rough draft of the proposed README.md file.

Thanks,
Armstrong

**Comment by germonprez** [comment]
Hi @foundjem 

Thanks!!

Could you make these changes in a pull request and the we could see them that way? If that isn't super clear, I can take what you have and create the PR.

**Comment by jgbarah** [comment]
We think this is done now, with the latest pull requests on that file.
