### ISSUE TITLE
GMD Goals for 2019

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-gmd#60]
We are creating a gmd goals document.

Here is the working document
https://docs.google.com/document/d/1CkzlCT1hi9OI1SQf_GAZSsNv9o3Po25x8wC5G424d2U/edit

**Comment by jgbarah** [comment]
I share the general lines I see in that document. Should we convert it into a PR, and eventually merge it? I suggest naming it ROADMAP.md (which is customary in some repos), and then making it evolve to a real roadmap if we want.

**Comment by jgbarah** [comment]
We already have a first roadmap, so we can close this.
