### ISSUE TITLE
What is the problem that this project is trying to solve?

### ISSUE THREAD

**Issue by abitrolly** [chaoss/wg-gmd#66]
GMD metrics is not a problem - it is a way. Measuring open source projects is also not a problem - it is a way. What I am missing from this project is motivation in terms of final goal. What is the problem to dedicate time and money to this GMD metrics?

https://medium.com/@jakemendel/seriously-whats-your-startup-s-problem-b3a884c54ab4

**Comment by jgbarah** [comment]
Thanks for the feedback. I think we all know metrics in general (not only GMD metrics) are not a problem, but a try to provide data to inform a decision or work towards solving a problem.

In this case, we're trying to organize the "problem" in focus areas, each trying to address some goals. For example, if you have a look at the [Code Development focus area](https://github.com/chaoss/wg-gmd/blob/master/focus_areas/code_development.md), the scope is

> Aspects related to how the source code changes over time, and the mechanisms that the project has to perform and control those changes.

and within this scope, the goals are:

> * Activity: Learning about hwo much activity in involved in changing (or adding) code
> * Efficiency: Learning how effective new code is merged into the code base
> * Quality: Learning about the processes to improve/review quality that are used (for example: testing, code review)

All of those are goals that could be relevant for a specific case, or not. But in case they are relevant for your case (and there is always a *you* deciding what's relevant), we propose the corresponding list of questions, that would help you in reaching that goal, and of metrics, that should help you to answer those metrics.

Does this explanation address your concerns?

**Comment by abitrolly** [comment]
My concern is not addressed. From the front page

> Growth, Maturity and Decline is a working group focused on the lifecycle of open source projects.

What is missing here are people. In my country outsourcing services is the primary business. Most people are busy working in corporations selling their hours and less and less have time to maintain open source infrastructure.

Open source started as a community, but in corporate world, treating people as resources, managing product lifecycles, community doesn't matter. The less people communicate, less distracted, the more effective their neural network are processing code. This is the loaded question I had. What problem will you solve once you get all the metrics without people?

**Comment by jgbarah** [comment]
@abitrolly can we close this issue, and if you find it convenient, continue the discussion in the mailing list?

**Comment by jgbarah** [comment]
Since there is no further comment, I'm closing this for now. Anyone, feel free to reopen if you feel it is convenient to follow up here.
