### ISSUE TITLE
Preparing the talk about the WG at CHAOSSCon EU 2019

### ISSUE THREAD

**Issue by jgbarah** [chaoss/wg-gmd#69]
We have this talk at CHAOSSCon EU 2019 for presenting the working group. We need to prepare it. This is just the reminder for that ;-)

**Comment by sgoggins** [comment]
I created a document and shared with @jgbarah

**Comment by jgbarah** [comment]
I'm late with this, I hope to work on it during the net few days. Sorry for my delay.

**Comment by GeorgLink** [comment]
Could you please provide a short description that we can put on the CHAOSScon schedule.

**Comment by jgbarah** [comment]
A short description could be (@sgoggins please modify as you may wish):

The GMD working group is exploring metrics related to growth-maturity-decline and other focus areas (such as risk). Our idea is to go top down, from the definition of the focus areas down to the goals that we want to fulfill in those areas, the questions that we would like to answer to reach those goals, and finally the metrics that could help us to better answer those questions. We also intend to work in reference implementations for the metrics. In parallel, we also work bottom-up, by collecting use case from real life.

This will be a workshop to explain all of this in more detail, to also explain our procedures, and how anyone can contribute. The workshop will also include a discussion on the current status of the working group, and on specific aspects of the focus areas, goals, questions and metrics we're considering. Anyone is welcome to submit issues and pull requests in advance, to propose topics of their interest.

**Comment by GeorgLink** [comment]
Thank you, I added the description to our CHAOSScon schedule:

https://chaoss.community/chaosscon-2019-eu/#user-content-jesus-m-gonzalez-barahona

**Comment by jgbarah** [comment]
@sgoggins have a look at the deck. I think we could publish it as a first draft.

**Comment by sgoggins** [comment]
View only link to slides: https://docs.google.com/presentation/d/1KT7hu3x-4tmlDnU0WHrZ9xo3_x294N0wuni6fIaiNZE/edit?usp=sharing

**Comment by GeorgLink** [comment]
Thank you for the slides. A current version is now on the CHAOSScon schedule website.

**Comment by jgbarah** [comment]
The session on GMD happened during CHAOSSCon EU 2019. I think we can close this.
