### ISSUE TITLE
GMD: Closed Issue Resolution Duration

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/wg-gmd#7]
Following #1,
[Closed issue resolution duration](https://github.com/chaoss/metrics/blob/master/activity-metrics/closed-issue-resolution-duration.md). As the name suggests: is this the time since an issue has been resolved? Again, do we look at all the issues or do we take an average?

Also, the definitions might need some improvement.

**Comment by jgbarah** [comment]
I agree with @GeorgLink for the definition. To make it more clear from the name, I would change the name to "time-to-resolution of closed issues", or maybe more clear, "time-to-close of closed issues".

WRT aggregation, same comments that those in #6 apply.

In addition, calculating it for specific periods of time (as @GeorgLink) suggests, is sensible, but maybe that depends on the granularity of the "evolution periods" that we're using in an specific case, something that I guess applies to almost any metric.

**Comment by jgbarah** [comment]
I think this is closed now, by #24.
