### ISSUE TITLE
GMD: first response to issue duration

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/wg-gmd#8]
Following #1, the definition states: *Time between a new issue is opened and a maintainer responds*. 
- Who is considered to be a maintainer? In the raw index, the users have 5 types of author_association: None, Owner, Collaborator, Contributor and Member. So are the latter 4 the maintainers for that project?
- What can be considered as a response? A reaction or a comment?

metric: [first response to issue duration](https://github.com/chaoss/metrics/blob/master/activity-metrics/first-response-to-issue-duration.md).

**Comment by jgbarah** [comment]
> So are the latter 4 the maintainers for that project?

I think we could start that way...

> What can be considered as a response? A reaction or a comment?

Again, I think we could start that way...

**Comment by aswanipranjal** [comment]
These still have to be implemented so that we can calculate them from the enriched indices directly as I mentioned in chaoss/grimoirelab-elk#364.  I'll start working on this.
