### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by awaiken** [chaoss/wg-gmd#89]
I'm getting a 404 error when trying to access the value and risk metrics.

**Comment by klumb** [comment]
Hi @awaiken, thanks for submitting this issue. 
I am unable to duplicate this error. Could you paste the URL you are trying to access into the comments?

**Comment by jgbarah** [comment]
Ping @awaiken, can you say if you can still see this? Specific link, please.

**Comment by awaiken** [comment]
Hello Jesus, I’m traveling this week but I’ll try and replicate the error tomorrow and send you a screen shot.


Regards,

Andrew Aitken
GM & Global Open Source Practice Leader
m: 650-704-6321, in/opensourcestrategy/
Wipro Limited

[http://marketing.wiprodigital.com/apps/wipro-esig/assets/images/logo-01.jpg]

**Comment by jgbarah** [comment]
Great. Thanks! Telling in which page is the error, and which link in it is failing could be good enough. It seems we cannot find it ;-)

**Comment by s-ankur** [comment]
I think @awaiken is referring to the links to Risk and Value Focus areas in the README.md.
