### ISSUE TITLE
New contributors

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/wg-gmd#9]
Following #1 
How should new contributors be calculated? 

By the commit that a user produces and looking at the first commit when the user produced it? Will that user then be a new contributor for that month?

**Comment by jgbarah** [comment]
We can split the metric in "new contributor for ..." where we have several kinds of contributors:

* merged commit (a commit by this person first appears in the git repo)
* opened issue (this person opens an issue for the first time)
* closed issue  (this person closes an issue for the first time)
* opened pull request (this person opens a pull request for the first time)
* merged (accepted) pull request (this person gets accepted a pull request of them for the first time)
* closed (merged or not) pull request (this person gets a pull request closed for the first time)
* review (this person reviews a pull request for the first time)
* message posted (this person posts a message to a mailing list for the first time)

...and so on.

Then, we could also aggregate, such as "new contributors of any kind during this month".

What do you think?

**Comment by aswanipranjal** [comment]
Sounds like a good idea! But this too requires us to better enrich the indices and collect more data. But all these combined will give us good insights about the communities growth and outreach.

**Comment by aswanipranjal** [comment]
@jgbarah: as per the [discussions on the mailing lists](https://lists.linuxfoundation.org/pipermail/oss-health-metrics/2018-June/000707.html), these metrics have to be derived and time bound, right?
