### ISSUE TITLE
Include Code of Conduct as Top Level Document

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-gmd#93]
The CoC can be copied from here; 

https://github.com/chaoss/governance/blob/master/code-of-conduct.md

This would keep aligned with the display D&I is doing.

**Comment by vchrombie** [comment]
@sgoggins I know that you are assigned to this issue. But I want to ask, can I solve this issue?

**Comment by jgbarah** [comment]
@vchrombie please go ahead!

**Comment by vchrombie** [comment]
There are few, very minor grammatical mistakes in the [CoC](https://github.com/chaoss/governance/blob/master/code-of-conduct.md). You can view the changes here https://github.com/chaoss/governance/compare/master...vchrombie:add-CoC

Is it relevant?
Is there any particular procedure to be followed to change it or a PR to the CoC of chaoss/governance works fine?

**Comment by GeorgLink** [comment]
Great find. Yes, a pull request to chaoss/governance would be the best way
to help.

**Comment by vchrombie** [comment]
I think this can be closed now. 
@sgoggins

**Comment by sgoggins** [comment]
We can close this since its merged.
